version: "3.9"
services:
    mysql_users:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: usersDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3307
        expose:
            - 3307
        container_name: mysql_users
        ports:
            - 3307:3307
        volumes:
            - db-users:/var/lib/mysql
    users:
        image: doviscarcelli/users-amd64
        platform: linux/amd64
        build:
            dockerfile: Dockerfile
            context: ./users
        env_file:
            - ./users/.env
        container_name: users
        ports:
            - "3001:3001"
        entrypoint: ["sh", "-c", "npx prisma migrate deploy; npm run dev"]
        depends_on:
            - mysql_users
            # - minio-users
        restart: always

    mysql_restaurants:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: restaurantsDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3308
        container_name: mysql_restaurants
        ports:
            - 3308:3308
        expose:
            - 3308
        volumes:
            - db-restaurants:/var/lib/mysql
    restaurants:
        image: doviscarcelli/restaurants
        build:
            dockerfile: Dockerfile
            context: ./restaurants
        container_name: restaurants
        ports:
            - "3002:3002"
        env_file:
            - ./restaurants/.env
        depends_on:
            - mysql_restaurants
            # - minio-restaurants
        restart: always
        entrypoint: ["sh", "-c", "npx prisma migrate deploy; npm run dev"]

volumes:
    db-users:
    db-restaurants:
    # db-reservations:
    # minio-users-data:
    # minio-restaurants-data:
