version: "3.9"
services:
    mysql_users:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: usersDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3306
        container_name: mysql_users
        ports:
            - 3307:3306
        expose:
            - 3307
        volumes:
            - db-users:/var/lib/mysql
        networks:
            - users-network

    postgres_restaurants:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: restaurantsDB
            # POSTGRES_PORT: 3306
        container_name: postgres_restaurants
        ports:
            - 3308:5432
        expose:
            - 3308
        volumes:
            - db-restaurants:/var/lib/postgres
        entrypoint: >
            bash -c "
              /usr/local/bin/docker-entrypoint.sh postgres &
              while ! pg_isready -h localhost -p 5432 > /dev/null 2>&1; do sleep 1; done
              apt-get update &&
              apt-get install -y postgis &&
              PGPASSWORD=admin psql -h localhost -U admin restaurantsDB -c 'CREATE EXTENSION IF NOT EXISTS postgis;' &&
              tail -f /dev/null
            "
        networks:
            - restaurants-network

    mysql_reservations:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: reservationsDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3306
        container_name: mysql_reservations
        ports:
            - 3309:3306
        expose:
            - 3309
        volumes:
            - db-reservations:/var/lib/mysql
        networks:
            - reservations-network

    minio-users:
        image: minio/minio
        restart: always
        container_name: minio-users
        ports:
            - 9001:9001
            - 9091:9091
        volumes:
            - minio-users-data:/data
        command: server /data --address :9001 --console-address :9091
        environment:
            - "MINIO_ROOT_USER=root"
            - "MINIO_ROOT_PASSWORD=root12345"
        networks:
            - users-network

    createbucket-users:
        image: minio/mc
        container_name: minio_createbucket_users
        depends_on:
            - minio-users
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add --api s3v4 minio http://minio-users:9001 root root12345;
            /usr/bin/mc mb minio/avatars;
            /usr/bin/mc anonymous set download minio/avatars;
            exit 0;
            "
        networks:
            - users-network

    minio-restaurants:
        image: minio/minio
        restart: always
        container_name: minio-restaurants
        ports:
            - 9002:9002
            - 9092:9092
        volumes:
            - minio-restaurants-data:/data
        command: server /data --address :9002 --console-address :9092
        environment:
            - "MINIO_ROOT_USER=root"
            - "MINIO_ROOT_PASSWORD=root12345"
        networks:
            - restaurants-network

    createbucket-restaurants:
        image: minio/mc
        container_name: minio_createbucket_restaurants
        depends_on:
            - minio-restaurants
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add --api s3v4 minio http://minio-restaurants:9002 root root12345;
            /usr/bin/mc mb minio/images;
            /usr/bin/mc anonymous set download minio/images;
            exit 0;
            "
        networks:
            - restaurants-network

    users:
        build:
            dockerfile: Dockerfile
            context: ./users
        container_name: users
        ports:
            - "3001:3001"
        environment:
            - DATABASE_URL=mysql://root:root@mysql_users:3306/usersDB
        volumes:
            - .:/app
        depends_on:
            - mysql_users
            - minio-users
        restart: always
        entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
        networks:
            - gateway
            - users-network

    restaurants:
        build:
            dockerfile: Dockerfile
            context: ./restaurants
        container_name: restaurants
        ports:
            - "3002:3002"
        environment:
            - DATABASE_URL=postgresql://admin:admin@postgres_restaurants:5432/restaurantsDB
        volumes:
            - .:/app
        depends_on:
            - postgres_restaurants
            - minio-restaurants
        restart: always
        entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

        networks:
            - gateway
            - restaurants-network

    reservations:
        build:
            dockerfile: Dockerfile
            context: ./reservations
        container_name: reservations
        ports:
            - "3003:3003"
        environment:
            - DATABASE_URL=mysql://root:root@mysql_reservations:3306/reservationsDB
        volumes:
            - .:/app
        depends_on:
            - mysql_reservations
        restart: always
        entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
        networks:
            - gateway
            - reservations-network

    nginx-proxy:
        build:
            dockerfile: Dockerfile
            context: ./proxy
        container_name: nginx-proxy
        depends_on:
            - users
            - restaurants
            - reservations
        ports:
            - "3000:3000"
        networks:
            - gateway

volumes:
    db-users:
    db-restaurants:
    db-reservations:
    minio-users-data:
    minio-restaurants-data:

networks:
    gateway:
        driver: bridge
    users-network:
    restaurants-network:
    reservations-network:
