version: "3.9"
services:
    mysql_users:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: usersDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3307
        expose:
            - 3307
        container_name: mysql_users
        ports:
            - 3307:3307
    users:
        image: doviscarcelli/users-amd64
        platform: linux/amd64
        build:
            dockerfile: Dockerfile
            context: ./users
        env_file:
            - ./users/.env
        container_name: users
        ports:
            - "3001:3001"
        # volumes:
        # - .:/app
        entrypoint: ["sh", "-c", "npx prisma migrate deploy; npm run dev"]
        depends_on:
            - mysql_users
            # - minio-users
        restart: always
volumes:
    db-users:
    db-restaurants:
    db-reservations:
    minio-users-data:
    minio-restaurants-data:
