version: "3.9"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_TCP_PORT: 3306
        container_name: mysql_users
        ports:
            - 3307:3306
        expose:
            - 3307
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - userNet

    adminer:
        image: adminer
        restart: always
        container_name: adminer_users
        ports:
            - 8081:8080
        expose:
            - 8081
        networks:
            - userNet

    app:
        build:
            context: ./
        container_name: users
        ports:
            - "3001:3001"
        environment:
            - DATABASE_URL=mysql://root:root@mysql_users:3306/usersDB
        volumes:
            - ./src:/app/src:z
        networks:
            - userNet
        depends_on:
            - db
        entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

networks:
    userNet:

volumes:
    db-data: