version: "3.9"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - restaurantNet

    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 8080:8080
        networks:
            - restaurantNet

    app:
        build:
            context: ./
        container_name: restaurants
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=mysql://root:root@mysql:3306/restaurantsDB
        volumes:
            - ./src:/app/src:z
        networks:
            - restaurantNet
        depends_on:
            - db
        command: npx prisma migrate deploy

networks:
    restaurantNet:

volumes:
    db-data:
